#! /usr/bin/env python3
from sys import argv


def get_index(notes, marker_id):
    if not marker_id in notes: return -1
    
    index = notes.find(marker_id)
    index = notes.find("}", index) - 1
    return index


def add_dungeon(notes_filename, marker_id, dungeon_link):
    with open(f"{notes_filename}.txt", "r") as file:
        notes  = file.read()

    index = get_index(notes, marker_id)
    if index == -1: raise ValueError(f"{marker_id} isn't a known marker")
    
    notes = notes[: index] + fr'<iframe style=\"height: 33vh\" src=\"{dungeon_link}\" sandbox=\"allow-scripts allow-same-origin\"></iframe>' + notes[index: ]

    with open(f"{notes_filename}.txt", "w") as file:
        file.write(notes)


notes_filename, marker_id, dungeon_link = argv[1], argv[2], argv[3]
add_dungeon(notes_filename, marker_id, dungeon_link)

